kind: Pod
apiVersion: v1
metadata:
  name: ${NAME}
spec:
  containers:
  - name: deeplearning-container
    tty: true
    image: docker.io/ak3636/deeplearning:latest
    imagePullPolicy: Always

      #"/hooks/startup.sh"
    command: ${CMD}
    args: ${ARGS}
    lifecycle:
      #postStart:
        #exec:
          #command: ["/bin/sleep", "1"]
      preStop:
        exec:
          command: ["/hooks/stop.sh"]
    resources:
      limits:
        nvidia.com/gpu: ${NGPUS}
        ${MEM_LIMIT}
      requests:
        nvidia.com/gpu: ${NGPUS}
        ${MEM_REQ}

    volumeMounts:

    - name: ssh-secret-volume
      mountPath: "/root/ssh_mount"
    - name: dshm
      mountPath: /dev/shm
    - name: experiments
      mountPath: /experiments
              
  nodeSelector:
    #kubernetes.io/hostname: k8s-gpu-02.calit2.optiputer.net
    #kubernets.io/hostname:  k8s-ravi-01.calit2.optiputer.net
    ${NODE_HOSTNAME}
  restartPolicy: Never
  volumes:
    - name: ssh-secret-volume
      secret:
        ${SSH_KEY_NAME}
    - name: dshm
      emptyDir: 
        medium: Memory
    - name: experiments
      flexVolume:
        driver: ceph.rook.io/rook
        fsType: ceph
        options:
          fsName: nautilusfs
          clusterNamespace: rook
          path: /mc-lab
          mountUser: mc-lab
          mountSecret: ceph-fs-secret
